Better command argument reader
volatusveritas/desc-tools pull request #2
Opened 2022-01-17 18:46 UTC by arthurbacci

2022-01-17 20:31 UTC, volatusveritas reviewed
It works, generally speaking. I would advise you to choose better variable names next time. Had some variables had a name with more than a single character, I could probably have understood what the functions did in a third or the time I spent doing so. Thanks for the PR once again.

2022-01-17 20:31 UTC, volatusveritas commented on src/command.cpp
> +    get_until(std::string_view &i, std::string_view v)
+ Whenever possible, don't use one letter parameter names.
+ The type of `v` could be `const char *`, or simply `char` (because you're using it to find a single character) which would make this more obvious and avoid the need to create a `string_view` object. (For more info, read [the find_first_of documentation](https://en.cppreference.com/w/cpp/string/basic_string_view/find_first_of), specifically on overloads 2 and 3.

2022-01-17 20:31 UTC, volatusveritas commented on src/command.cpp
Types of `c` and `ret` are not complex enough for `auto` to be useful here. Avoid type obfuscation/implicit typing whenever possible or feasible.

2022-01-17 20:31 UTC, volatusveritas commented on src/command.cpp
> +        while (ln.substr(0, 1) == " ")
Use the `operator[]` access specifier as `[0]` or `.front()` here instead. This just makes the code harder to read with no benefit.

2022-01-17 20:31 UTC, volatusveritas commented on src/command.cpp
> +#include <stdexcept>
Where do you use this header in this file?

2022-01-17 20:31 UTC, volatusveritas commented on src/main.cpp
> +    std::string_view ln = line;
Creating an object for single-function usage is bad practice. A good alternative would be to have this `string_view` be created from the source `string` in the `popArgument` function.

2022-01-17 21:00 UTC, arthurbacci commented on src/command.cpp
> +        while (ln.substr(0, 1) == " ")
> Use the `operator[]` access specifier as `[0]` or `.front()` here instead. This just makes the code harder to read with no benefit.

With `substr` we will have "" if `ln` is empty, instead of getting an overflow.

2022-01-17 21:02 UTC, arthurbacci commented on src/command.cpp
> +        while (ln.substr(0, 1) == " ")
`at` could be faster but it would need `try` and `catch` and it would make the code longer, another option would be to use `!ln.empty() && ' ' == ln.front()`

2022-01-17 21:03 UTC, arthurbacci commented on src/command.cpp
> +#include <stdexcept>
Forgot to remove.

2022-01-17 21:03 UTC, arthurbacci commented on src/main.cpp
> +    std::string_view ln = line;
> Creating an object for single-function usage is bad practice. A good alternative would be to have this `string_view` be created from the source `string` in the `popArgument` function.

It will not be possible since we need this string_view to be a mutable reference.

2022-01-17 21:04 UTC, arthurbacci commented on src/command.cpp
> Types of `c` and `ret` are not complex enough for `auto` to be useful here. Avoid type obfuscation/implicit typing whenever possible or feasible.

Cringe.

2022-01-18 18:17 UTC, volatusveritas requested changes
Apart from the aforementioned tips, I have nothing else to say about this. Beautiful code. Thank you once again.

2022-01-18 21:26 UTC, arthurbacci commented on src/command.cpp
> +        for (;;)
> Prefer `while (true)` instead. No performance overhead, with better readability. Also, never use `while (1)` instead of `while (true)`.

There's no better readability, anyone with the minimum understanding of C/C++ knows what `for (;;)` does and knows that it is the same as `while (1)`/`while (true)`

2022-01-18 21:31 UTC, arthurbacci commented on src/command.cpp
> +    splitStringView(std::string_view str, char v)
> If one of the arguments is an aggregate type you do not wish to copy (for performance reasons), consider introducing it as a reference. If you do not intend on modifying such aggregate type, consider making it constant. In this case, I would recommend you to use both, as in `const std::string_view &str`.

`std::string_view` is not a container like `std::string`, it is just a pointer with a length, having only 128 bits (16 bytes) in most platforms, since it is a small data type, in most cases we have more performace copying it than referencing, that's why you don't use references to integers or any other integral type.

2022-01-18 21:54 UTC, volatusveritas commented on src/command.cpp
> +        while (ln.substr(0, 1) == " ")
Isn't `at` a `std::string` element access function? Is it also implemented in `std::string_view`?

2022-01-18 21:59 UTC, volatusveritas commented on src/command.cpp
> +        for (;;)
Everyone with the minimum understanding of C/C++ can also conclude that `!(!(true == !false))` is `true`. All you need to do is spend some seconds thinking. But I vouch you'd rather read the latter than the former.

2022-01-18 22:00 UTC, volatusveritas commented on src/command.cpp
> +    splitStringView(std::string_view str, char v)
Thanks for the info.

2022-01-18 22:06 UTC, volatusveritas commented on src/main.cpp
> +    std::string_view ln = line;
I later came to understand this. With that in mind, try keeping functions "atomic" (minimal units of behavior that can be freely and safely repeated or accumulated). Either that and explicitly call a function to advance the view, or naming it something like `advance_until` which actually explicits the fact it moves the view.

2022-01-18 22:14 UTC, merged